name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8.15.4
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Restore Turborepo cache
        uses: actions/cache@v3
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ hashFiles('**/package.json', 'pnpm-lock.yaml', 'turbo.json') }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Build metrics toolkit
        run: pnpm --filter @deterministic-agent-lab/metrics build

      - name: Collect reproducibility metrics
        run: pnpm --filter @deterministic-agent-lab/metrics exec node dist/index.js replay --iterations 50 --output metrics/reports/replay-metrics.md

      - name: Publish reproducibility report
        uses: actions/upload-artifact@v4
        with:
          name: replay-metrics
          path: metrics/reports/replay-metrics.md
